### ISSUE TITLE
Share app state across devices

### ISSUE THREAD

**Issue by buzz** [buzz/newsdash#6]
As this app works serverless (and stores app state in LocalStorage for now), sharing across devices introduces a challenge.

Approaches:

- [x] Manually transfer serialized feed info to another machine (import/export) #8
- [ ] ~~Use a (free) web service to store and retrieve (partial) app state #9~~
- [x] Implement a simple backend that stores user data #33
